CREATE DATABASE IF NOT EXISTS Petition;
USE Petition;

CREATE TABLE Utilisateur (
    IDU INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    MotDePasse VARCHAR(255) NOT NULL, 
    Role ENUM('user', 'admin') DEFAULT 'user', 
    DateInscription DATETIME DEFAULT CURRENT_TIMESTAMP,
    Actif BOOLEAN DEFAULT TRUE
);
CREATE TABLE Petition (
    IDP INT AUTO_INCREMENT PRIMARY KEY,
    TitreP VARCHAR(200) NOT NULL,
    DescriptionP TEXT NOT NULL,
    DateAjoutP DATETIME DEFAULT CURRENT_TIMESTAMP,
    DateFinP DATE,
    NomPorteurP VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL,
    IDU INT, 
    FOREIGN KEY (IDU) REFERENCES Utilisateur(IDU) ON DELETE SET NULL
);
CREATE TABLE Signature (
    IDS INT AUTO_INCREMENT PRIMARY KEY,
    IDP INT NOT NULL,
    NomS VARCHAR(100) NOT NULL,
    PrenomS VARCHAR(100) NOT NULL,
    PaysS VARCHAR(100),
    DateS DATETIME DEFAULT CURRENT_TIMESTAMP,
    HeureS TIME DEFAULT (CURRENT_TIME),
    EmailS VARCHAR(150) NOT NULL,
    IDU INT, 
    FOREIGN KEY (IDP) REFERENCES Petition(IDP) ON DELETE CASCADE,
    FOREIGN KEY (IDU) REFERENCES Utilisateur(IDU) ON DELETE SET NULL,
    UNIQUE KEY unique_signature (IDP, EmailS)
);